
# Dependencies
markdown:         kramdown

# Permalinks
#permalink:        pretty

# Setup
title:            'Statistics'
tagline:          'from http://cnx.org/contents/30189442-6998-4686-ac05-ed152b91b9de@18.12 (CC-BY)'
url:              https://github.com/philschatz/statistics-book
origin:           http://cnx.org/contents/30189442-6998-4686-ac05-ed152b91b9de@18.12

author:
  name:           'Openstax'
  url:            https://github.com/openstax

paginate:         5

# Custom vars
version:          18.12

bookviewer:       http://philschatz.com/book-viewer

